# Problem staement 1

In [ ]:
''' 
Problem Statement: -
Kitabi Duniya, a famous book store in India, which was established before Independence,
the growth of the company was incremental year by year, but due to online selling of books and wide 
spread Internet access its annual growth started to collapse, seeing sharp downfalls, you as a Data Scientist help this 
heritage book store gain its popularity back and increase footfall of customers and provide ways the business can improve exponentially, 
apply Association RuleAlgorithm, explain the rules, and visualize the graphs for clear understanding of solution.
1.) Books.csv
'''

In [5]:
# import the requerd librarise to load the data file
import pandas as pd
df = pd.read_csv('book.csv')
df.head()

,ChildBks,YouthBks,CookBks,DoItYBks,RefBks,ArtBks,GeogBks,ItalCook,ItalAtlas,ItalArt,Florence
0,0,1,0,1,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0
3,1,1,1,0,1,0,1,0,0,0,0
4,0,0,1,0,0,0,1,0,0,0,0

In [7]:
# Data Preprocessing 
# check the null values
df.isnull().sum()

ChildBks     0
YouthBks     0
CookBks      0
DoItYBks     0
RefBks       0
ArtBks       0
GeogBks      0
ItalCook     0
ItalAtlas    0
ItalArt      0
Florence     0
dtype: int64

In [9]:
# drop duplicates if any 
df.drop_duplicates(inplace=True)

In [11]:
# Standerize the data 
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
sd.fit_transform(df)

array([[-1.25723711,  1.1055416 , -1.46193533, ..., -0.43542058,
        -0.4853053 , -0.68402479],
       [ 0.79539491, -0.90453403, -1.46193533, ..., -0.43542058,
        -0.4853053 , -0.68402479],
       [-1.25723711, -0.90453403, -1.46193533, ..., -0.43542058,
        -0.4853053 , -0.68402479],
       ...,
       [ 0.79539491, -0.90453403,  0.68402479, ...,  2.2966301 ,
        -0.4853053 ,  1.46193533],
       [ 0.79539491,  1.1055416 ,  0.68402479, ...,  2.2966301 ,
         2.06055857, -0.68402479],
       [-1.25723711, -0.90453403,  0.68402479, ..., -0.43542058,
         2.06055857,  1.46193533]])

In [12]:
# convert the dataset into list of lists
# why we need to convert it into list formate
# 1. transaction data format: 
    # Apriori algorithm only work on Trasactional data where each transaction is collection of items.
    # eg. ['name','class']
# 2. Apriori algorothm input 
    # Input should be in the list format
# 3. Transaction Encoding
    # when the data is in the list format then mlxtend can easily apply transactionencoders
    # to convert the data into a formate suitable for the Apriori algorithm
    # TransactionEncoder transform the list of lists into a "one-hot-encoded" Dataframe
    # each column represents an item, and each row corresponds to a transaction.
    # the value is 1 if an item is present in the transaction 
    # 0 if it is absent.
# process
# initilize the empty list 
tran = []
for i in range(0, len(df)):
    tran.append([str(df.values[i,j]) for j in range(0, len(df.columns)) if pd.notna(df.values[i,j])])
    

print(tran)

[['0', '1', '0', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'], ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1'], ['0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0'], ['0', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0'], ['1', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '0', '1', '1', '1', '0', '0', '1', '1', '0'], ['1', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0'], ['1', '1', '1', '0', '0', '1', '0', '0', '0', '0', '1'], ['0', '1', '1', '1', '0', '1', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '0', '1', '1', '0', '0', '0'], ['0', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1'], ['1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '0'], ['1', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0'], ['0', '0', '1', '1', '0', '1', '0', '0', '0', '1', '0'], ['0', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0'], ['1', '1', '1', '0', '1', '1', '1', '1', '0', '0', '0'], ['0', '0', '1', '0', '0', '0', '0', '1', '0', '0', '0'], ['0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0'], ['1', '1', '0', '1', '1', '1', '0', '0', '0', '0', '0'], ['0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '1', '1', '1', '0', '0', '0'], ['1', '0', '1', '1', '1', '1', '1', '1', '1', '1', '0'], ['1', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '1', '1', '0', '0', '0', '0'], ['0', '1', '1', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '1', '0', '0', '0', '0', '1'], ['1', '0', '1', '0', '0', '1', '1', '1', '0', '1', '1'], ['1', '1', '0', '0', '0', '1', '1', '0', '0', '0', '0'], ['0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '0'], ['1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0'], ['0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '0', '1', '0', '0', '0', '0'], ['1', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0'], ['1', '0', '1', '0', '0', '0', '1', '1', '0', '0', '0'], ['1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '0', '1', '1', '0', '0', '0'], ['0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '1'], ['0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '0'], ['1', '0', '0', '1', '0', '1', '1', '0', '0', '0', '1'], ['0', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0'], ['0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0'], ['0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0'], ['0', '0', '0', '0', '0', '0', '1', '0', '0', '0', '1'], ['0', '0', '1', '1', '0', '1', '1', '1', '0', '1', '0'], ['0', '1', '0', '0', '1', '1', '0', '0', '1', '0', '0'], ['1', '1', '1', '1', '0', '1', '0', '1', '0', '1', '1'], ['0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '0'], ['0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '1'], ['0', '0', '1', '1', '0', '1', '0', '1', '0', '1', '0'], ['1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1'], ['1', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '0', '1', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0'], ['1', '0', '1', '0', '0', '0', '0', '1', '0', '0', '0'], ['0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '0'], ['0', '0', '1', '1', '1', '1', '0', '0', '0', '0', '0'], ['0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '1', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0'], ['0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '1'], ['1', '1', '1', '1', '1', '1', '0', '1', '1', '1', '0'], ['1', '1', '1', '1', '0', '1', '0', '0', '0', '0', '1'], ['1', '1', '1', '0', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '0', '0', '0', '0', '0', '0'], ['0', '1', '1', '0', '0', '0', '0', '1', '0', '0', '0'], ['0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '0', '1', '1', '0', '1', '0', '1', '0', '0'], ['1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '1'], ['1', '0', '1', '0', '0', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '0', '1', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '0', '0', '1', '0', '0', '0', '0', '0'], ['0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '0', '0', '1', '1', '1', '0', '0', '0', '1'], ['1', '0', '1', '0', '1', '0', '0', '1', '0', '0', '1'], ['1', '0', '0', '1', '0', '0', '1', '0', '0', '0', '1'], ['1', '1', '1', '0', '1', '1', '0', '0', '0', '0', '0'], ['1', '1', '1', '1', '0', '0', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '1', '1', '1', '0', '0', '0'], ['1', '1', '0', '1', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '1', '1', '1', '0', '1', '1', '1'], ['1', '1', '0', '0', '0', '1', '1', '0', '0', '1', '0'], ['1', '1', '1', '1', '0', '1', '0', '1', '0', '1', '0'], ['1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '0'], ['1', '0', '0', '1', '1', '1', '1', '0', '0', '0', '0'], ['0', '1', '1', '1', '1', '1', '0', '1', '1', '1', '0'], ['0', '0', '1', '1', '1', '1', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '1', '0', '0', '1', '1', '0', '0', '0'], ['0', '1', '0', '0', '0', '1', '0', '0', '0', '0', '1'], ['0', '0', '0', '1', '0', '1', '1', '0', '0', '0', '1'], ['0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '1'], ['1', '0', '1', '1', '1', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '1', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '1', '1', '0', '0', '0', '1'], ['0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '1'], ['1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '0'], ['1', '0', '1', '1', '0', '1', '0', '1', '0', '1', '0'], ['1', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '0', '1', '0', '0', '0', '1'], ['1', '1', '1', '0', '1', '0', '1', '1', '1', '0', '0'], ['0', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0'], ['0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '1'], ['0', '1', '1', '0', '0', '0', '0', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '1', '1', '1', '1', '1', '1'], ['1', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0'], ['1', '1', '0', '1', '0', '1', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '0', '0', '0', '0', '0', '0'], ['0', '1', '0', '0', '1', '0', '0', '0', '1', '0', '0'], ['1', '0', '1', '1', '0', '1', '0', '1', '0', '0', '0'], ['1', '1', '1', '1', '0', '1', '0', '1', '0', '0', '0'], ['0', '1', '1', '0', '1', '0', '0', '1', '0', '0', '0'], ['0', '1', '1', '1', '0', '1', '1', '1', '0', '1', '0'], ['1', '1', '1', '0', '0', '1', '1', '1', '0', '0', '1'], ['1', '1', '1', '0', '0', '0', '1', '1', '0', '0', '0'], ['1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '0'], ['0', '0', '1', '0', '0', '1', '0', '0', '0', '1', '0'], ['1', '1', '1', '1', '0', '1', '1', '1', '0', '1', '0'], ['1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '0'], ['1', '0', '1', '0', '0', '1', '1', '1', '0', '0', '0'], ['0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '0'], ['0', '1', '1', '0', '0', '1', '0', '1', '0', '1', '0'], ['0', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0'], ['0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '1'], ['1', '1', '0', '0', '1', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '0', '0', '1', '1', '1', '0', '0', '0'], ['1', '0', '1', '0', '0', '1', '0', '0', '0', '0', '1'], ['1', '1', '1', '1', '1', '1', '0', '1', '0', '0', '0'], ['1', '1', '1', '1', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '1', '1', '0', '0', '0', '1'], ['1', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1'], ['0', '0', '1', '1', '0', '1', '1', '0', '0', '0', '1'], ['1', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '1', '1', '0', '0', '0', '0', '1'], ['1', '0', '1', '1', '1', '1', '0', '0', '1', '0', '0'], ['1', '1', '1', '1', '0', '1', '1', '1', '0', '0', '0'], ['1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0'], ['0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '1'], ['1', '1', '1', '0', '1', '1', '1', '1', '0', '1', '0'], ['0', '0', '1', '1', '0', '0', '1', '0', '0', '0', '0'], ['0', '0', '1', '1', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '0', '1', '1', '0', '0', '0'], ['1', '0', '0', '0', '1', '1', '1', '0', '1', '1', '0'], ['1', '0', '1', '1', '1', '1', '0', '1', '1', '1', '0'], ['1', '1', '0', '1', '1', '1', '1', '0', '0', '0', '0'], ['1', '0', '0', '1', '1', '0', '1', '0', '1', '0', '0'], ['1', '1', '1', '1', '1', '0', '1', '0', '0', '0', '1'], ['0', '1', '1', '1', '0', '0', '1', '1', '0', '0', '0'], ['1', '1', '0', '0', '1', '1', '1', '0', '0', '0', '1'], ['0', '0', '1', '1', '0', '1', '0', '1', '0', '0', '0'], ['0', '1', '1', '1', '1', '1', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0'], ['0', '1', '1', '1', '0', '1', '1', '1', '0', '1', '1'], ['1', '1', '0', '0', '1', '1', '1', '0', '1', '1', '0'], ['0', '0', '1', '1', '1', '0', '0', '1', '0', '0', '0'], ['0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '0', '0', '1', '0', '0', '0'], ['1', '0', '0', '1', '1', '1', '1', '0', '0', '0', '1'], ['0', '0', '0', '1', '0', '1', '0', '0', '0', '0', '1'], ['1', '1', '1', '0', '1', '1', '0', '1', '0', '0', '0'], ['0', '1', '0', '1', '1', '0', '1', '0', '0', '0', '0'], ['0', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0'], ['1', '1', '1', '0', '1', '0', '1', '1', '0', '0', '0'], ['1', '0', '0', '1', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '0', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '1', '1', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0'], ['1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '0', '1', '1', '0', '0', '1'], ['1', '0', '1', '0', '1', '1', '1', '0', '0', '0', '1'], ['1', '0', '0', '0', '1', '1', '1', '0', '0', '0', '0'], ['0', '1', '0', '0', '0', '0', '1', '0', '0', '0', '1'], ['0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1'], ['1', '1', '1', '1', '0', '0', '0', '1', '0', '0', '0'], ['0', '0', '1', '1', '0', '1', '0', '0', '0', '0', '0'], ['0', '0', '1', '0', '0', '1', '1', '0', '0', '0', '1'], ['1', '1', '1', '1', '0', '1', '1', '0', '0', '1', '0'], ['1', '1', '1', '0', '0', '1', '1', '0', '0', '0', '1'], ['1', '1', '1', '1', '0', '1', '1', '0', '0', '0', '1'], ['1', '0', '1', '0', '0', '1', '1', '1', '0', '0', '1'], ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'], ['0', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '0', '0', '0', '0', '1', '0', '0', '0'], ['0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '1'], ['1', '1', '1', '1', '0', '1', '1', '1', '0', '1', '1'], ['1', '0', '1', '1', '1', '0', '0', '0', '0', '0', '1'], ['1', '1', '1', '0', '0', '1', '1', '1', '0', '1', '1'], ['1', '1', '0', '1', '1', '0', '0', '0', '0', '0', '0'], ['1', '1', '1', '0', '1', '1', '1', '1', '0', '1', '1'], ['1', '1', '0', '1', '1', '1', '0', '0', '1', '1', '1'], ['1', '0', '1', '1', '1', '1', '0', '1', '0', '0', '0'], ['1', '1', '1', '1', '1', '1', '1', '1', '0', '0', '1'], ['0', '1', '0', '0', '1', '1', '1', '0', '1', '1', '1'], ['1', '1', '0', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '0', '0', '0', '1', '0', '0', '0'], ['1', '0', '1', '1', '0', '1', '1', '1', '0', '1', '1'], ['1', '1', '1', '1', '1', '0', '1', '1', '1', '0', '1'], ['1', '1', '1', '0', '1', '0', '0', '1', '1', '0', '0'], ['1', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '1', '1', '1', '1', '1', '1', '0'], ['0', '1', '1', '1', '0', '0', '0', '0', '0', '0', '1'], ['1', '0', '1', '1', '0', '1', '0', '0', '0', '1', '1'], ['1', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0'], ['1', '1', '0', '1', '1', '0', '0', '0', '1', '0', '0'], ['1', '1', '1', '1', '1', '0', '1', '1', '1', '0', '0'], ['0', '0', '0', '0', '0', '1', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '0', '0', '1', '1', '0', '0', '0'], ['1', '1', '1', '1', '1', '0', '0', '0', '1', '0', '0'], ['0', '0', '1', '1', '1', '0', '1', '0', '1', '0', '0'], ['0', '0', '0', '0', '1', '1', '0', '0', '0', '0', '1'], ['0', '1', '1', '1', '0', '0', '0', '1', '0', '0', '0'], ['1', '1', '1', '0', '1', '1', '1', '0', '0', '0', '0'], ['1', '0', '0', '1', '1', '1', '1', '0', '1', '1', '0'], ['1', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '0', '0', '1', '1', '0', '0'], ['1', '1', '1', '0', '1', '0', '1', '0', '0', '0', '1'], ['0', '1', '1', '0', '1', '1', '1', '0', '0', '0', '0'], ['1', '1', '1', '1', '1', '0', '0', '1', '1', '0', '0'], ['1', '1', '0', '0', '0', '1', '0', '0', '0', '1', '0'], ['1', '1', '1', '1', '1', '1', '0', '0', '0', '0', '1'], ['1', '0', '1', '1', '0', '0', '1', '1', '0', '0', '1'], ['1', '0', '1', '0', '1', '1', '1', '1', '0', '0', '0'], ['1', '1', '0', '0', '1', '0', '1', '0', '0', '0', '0'], ['0', '1', '1', '0', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '1', '0', '0', '1', '1', '1'], ['1', '0', '1', '0', '0', '1', '1', '0', '0', '0', '1'], ['1', '0', '1', '1', '1', '1', '0', '1', '0', '1', '1'], ['0', '0', '1', '1', '0', '1', '1', '0', '0', '0', '0'], ['1', '1', '1', '0', '0', '0', '1', '0', '0', '0', '1'], ['1', '0', '1', '0', '0', '0', '1', '0', '0', '0', '1'], ['1', '0', '0', '1', '0', '1', '0', '0', '0', '0', '1'], ['0', '1', '0', '1', '0', '1', '0', '0', '0', '1', '0'], ['1', '0', '1', '0', '1', '0', '0', '1', '0', '0', '0'], ['1', '0', '0', '0', '0', '1', '1', '0', '0', '1', '0'], ['1', '0', '1', '0', '1', '0', '1', '1', '1', '0', '1'], ['1', '1', '0', '1', '1', '1', '1', '0', '0', '0', '1'], ['1', '0', '0', '0', '0', '1', '0', '0', '0', '1', '0'], ['1', '0', '1', '1', '1', '1', '1', '1', '0', '0', '1'], ['0', '1', '1', '0', '1', '1', '1', '0', '0', '0', '1'], ['1', '0', '1', '0', '0', '1', '0', '1', '0', '1', '0'], ['0', '1', '1', '1', '1', '1', '0', '0', '0', '0', '1'], ['0', '0', '1', '0', '0', '1', '1', '0', '0', '1', '0'], ['1', '1', '1', '1', '0', '0', '1', '0', '0', '0', '1'], ['0', '1', '1', '0', '1', '1', '0', '0', '0', '0', '0'], ['0', '1', '1', '1', '1', '1', '1', '0', '0', '0', '0'], ['1', '1', '0', '0', '1', '0', '1', '0', '1', '0', '0'], ['1', '0', '1', '1', '0', '1', '0', '1', '0', '1', '1'], ['0', '1', '1', '1', '1', '0', '0', '0', '0', '0', '0'], ['0', '1', '1', '0', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '1', '0', '1', '1', '0', '0', '0', '0', '1'], ['0', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0'], ['0', '0', '1', '1', '1', '0', '0', '1', '1', '0', '0'], ['1', '0', '1', '1', '1', '0', '1', '0', '0', '0', '1'], ['1', '0', '1', '1', '1', '0', '0', '1', '0', '0', '0'], ['0', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0'], ['0', '0', '0', '0', '1', '0', '0', '0', '1', '0', '0'], ['1', '0', '0', '1', '1', '0', '0', '0', '0', '0', '0'], ['0', '0', '1', '1', '1', '1', '1', '1', '1', '1', '0'], ['1', '1', '0', '1', '1', '1', '0', '0', '0', '0', '1'], ['0', '0', '1', '1', '0', '1', '0', '0', '0', '0', '1'], ['1', '0', '1', '0', '1', '1', '0', '1', '1', '0', '0'], ['0', '1', '1', '1', '0', '1', '0', '1', '0', '1', '0'], ['1', '1', '1', '0', '1', '1', '0', '1', '0', '1', '0'], ['0', '0', '0', '1', '0', '1', '0', '0', '0', '1', '0'], ['0', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0'], ['0', '1', '1', '0', '0', '1', '0', '1', '0', '0', '0'], ['0', '1', '1', '0', '1', '0', '0', '0', '0', '0', '0'], ['0', '1', '0', '0', '1', '0', '1', '0', '0', '0', '0'], ['1', '0', '0', '0', '1', '0', '1', '0', '0', '0', '0'], ['0', '0', '1', '0', '1', '0', '1', '0', '0', '0', '1'], ['0', '1', '1', '0', '1', '0', '0', '1', '1', '0', '0'], ['1', '0', '0', '1', '0', '1', '1', '0', '0', '1', '1'], ['0', '1', '1', '0', '0', '0', '0', '1', '0', '0', '1'], ['1', '0', '1', '0', '0', '0', '0', '1', '0', '0', '1'], ['0', '0', '1', '1', '1', '1', '1', '0', '0', '0', '1'], ['0', '0', '1', '1', '0', '1', '1', '1', '0', '0', '1'], ['1', '0', '1', '1', '0', '1', '1', '0', '0', '0', '1'], ['1', '0', '1', '1', '1', '0', '1', '1', '1', '0', '0'], ['1', '1', '1', '0', '1', '1', '1', '1', '1', '1', '1'], ['0', '1', '1', '0', '0', '1', '1', '0', '0', '0', '1'], ['1', '1', '1', '0', '0', '1', '0', '1', '0', '0', '0'], ['1', '0', '1', '0', '1', '1', '1', '1', '0', '1', '1'], ['0', '0', '1', '0', '1', '0', '1', '1', '1', '0', '0'], ['1', '1', '1', '1', '1', '1', '0', '1', '0', '1', '0'], ['0', '0', '1', '1', '0', '0', '0', '0', '0', '0', '1'], ['1', '1', '1', '0', '1', '0', '0', '1', '0', '0', '0'], ['1', '0', '1', '0', '1', '1', '0', '1', '1', '1', '0'], ['0', '0', '0', '1', '1', '1', '0', '0', '0', '0', '0'], ['0', '0', '0', '1', '0', '0', '1', '0', '0', '0', '1'], ['0', '1', '1', '1', '1', '0', '0', '1', '0', '0', '1'], ['0', '0', '1', '0', '1', '0', '1', '0', '1', '0', '0'], ['1', '0', '1', '1', '0', '1', '0', '0', '0', '0', '1'], ['0', '0', '0', '1', '1', '1', '1', '0', '0', '0', '0'], ['1', '0', '1', '1', '1', '0', '0', '0', '1', '0', '0'], ['1', '1', '1', '0', '1', '0', '1', '1', '1', '0', '1'], ['0', '0', '1', '0', '1', '0', '1', '1', '0', '0', '0'], ['1', '0', '1', '0', '0', '0', '1', '1', '0', '0', '1'], ['1', '1', '0', '0', '0', '1', '0', '0', '0', '0', '0'], ['1', '0', '1', '0', '1', '0', '0', '0', '1', '0', '0'], ['1', '1', '1', '1', '1', '1', '1', '1', '0', '1', '0'], ['1', '0', '1', '1', '1', '0', '0', '1', '1', '0', '1'], ['1', '1', '1', '0', '1', '1', '0', '1', '1', '1', '0'], ['0', '0', '1', '0', '0', '1', '1', '1', '0', '1', '1']]

# Model building

In [16]:
# the Apriori algorithm identifies frequent itemsets and then uses these itemsets to generate association rules.
# use the apriori method from the mlxtend library to mine the frequnt items
# import the requierd librarise for Apriori 
from mlxtend.frequent_patterns import apriori, association_rules
from mlxtend.preprocessing import TransactionEncoder

# step 1 convert the data set into a formate suitable for apriori
te = TransactionEncoder()
te_arr = te.fit(tran).transform(tran)
df1 = pd.DataFrame(te_arr,columns=te.columns_)

In [18]:

# step 2 : apply the apriori algorith to find the frequent itemset 
fre_item = apriori(df, min_support=0.1, use_colnames=True)

C:\Users\anuradha\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\fpcommon.py:109: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [20]:
# step 3 : generate association rules from frequent itemset 
rule = association_rules(fre_item, metric='lift', min_threshold=1)

In [22]:
# output of the result 
print("Freuentnt itemset\n ")
print(fre_item)

Freuentnt itemset

      support                               itemsets
0    0.612500                             (ChildBks)
1    0.450000                             (YouthBks)
2    0.681250                              (CookBks)
3    0.490625                             (DoItYBks)
4    0.506250                               (RefBks)
..        ...                                    ...
152  0.106250   (CookBks, GeogBks, DoItYBks, ArtBks)
153  0.106250  (ItalCook, CookBks, DoItYBks, ArtBks)
154  0.103125     (RefBks, CookBks, GeogBks, ArtBks)
155  0.112500   (ItalCook, CookBks, GeogBks, ArtBks)
156  0.128125   (ItalArt, ItalCook, CookBks, ArtBks)

[157 rows x 2 columns]

In [24]:
print("\n association rule \n")
print(rule[['antecedents','consequents','support','confidence','lift']])

 association rule

           antecedents                   consequents   support  confidence  \
0           (ChildBks)                    (YouthBks)  0.300000    0.489796
1           (YouthBks)                    (ChildBks)  0.300000    0.666667
2           (ChildBks)                     (CookBks)  0.437500    0.714286
3            (CookBks)                    (ChildBks)  0.437500    0.642202
4           (ChildBks)                    (DoItYBks)  0.315625    0.515306
..                 ...                           ...       ...         ...
875  (CookBks, ArtBks)           (ItalArt, ItalCook)  0.128125    0.333333
876          (ItalArt)   (ItalCook, CookBks, ArtBks)  0.128125    0.672131
877         (ItalCook)    (ItalArt, CookBks, ArtBks)  0.128125    0.383178
878          (CookBks)   (ItalArt, ItalCook, ArtBks)  0.128125    0.188073
879           (ArtBks)  (ItalArt, ItalCook, CookBks)  0.128125    0.230337

         lift
0    1.088435
1    1.088435
2    1.048493
3    1.048493
4    1.050305
..        ...
875  2.601626
876  3.469064
877  2.608869
878  1.467890
879  1.797753

[880 rows x 5 columns]

In [26]:
''' 
Observation:

The rule (ChildBks) -> (YouthBks) with a confidence of 0.49 and a lift of 1.08 shows that customers who buy children's books also tend to buy youth books, though the relationship is moderately strong.
Similarly, (YouthBks) -> (ChildBks) with a higher confidence of 0.67 and a lift of 1.08 suggests a stronger tendency for customers who purchase youth books to also buy children's books.

This data-driven approach can help Kitabi Duniya regain its competitive edge in the market.
'''

" \nObservation:\n\nThe rule (ChildBks) -> (YouthBks) with a confidence of 0.49 and a lift of 1.08 shows that customers who buy children's books also tend to buy youth books, though the relationship is moderately strong.\nSimilarly, (YouthBks) -> (ChildBks) with a higher confidence of 0.67 and a lift of 1.08 suggests a stronger tendency for customers who purchase youth books to also buy children's books.\n\nThis data-driven approach can help Kitabi Duniya regain its competitive edge in the market.\n"

In [ ]:
''' 
Objective:1
The primary objective of this analysis is to help Kitabi Duniya, a heritage bookstore in India,
regain its market position and increase customer footfall. By applying the Association Rule Algorithm, 
the aim is to uncover meaningful relationships between different book categories that customers frequently purchase together. 
'''

# Problem Staement 2

In [ ]:
'''
Problem Statement: - 
The Departmental Store, has gathered the data of the products it sells on a Daily basis.
Using Association Rules concepts, provide the insights on the rules and the plots.
2.) Groceries.csv

'''

In [28]:
import pandas as pd 

# Correctly reading the CSV file with UTF-8 encoding
import pandas as pd
df5 = pd.read_csv('groceries.csv', on_bad_lines='skip')  # Skip problematic lines

# Display the DataFrame
print(df5)

             citrus fruit       semi-finished bread            margarine  \
0          tropical fruit                    yogurt               coffee
1              whole milk                       NaN                  NaN
2               pip fruit                    yogurt        cream cheese
3        other vegetables                whole milk       condensed milk
4              rolls/buns                       NaN                  NaN
...                   ...                       ...                  ...
6100               yogurt  long life bakery product                  NaN
6101                 pork         frozen vegetables               pastry
6102            ice cream  long life bakery product  specialty chocolate
6103    cooking chocolate                       NaN                  NaN
6104  semi-finished bread             bottled water                 soda

                   ready soups
0                          NaN
1                          NaN
2                 meat spreads
3     long life bakery product
4                          NaN
...                        ...
6100                       NaN
6101                       NaN
6102             specialty bar
6103                       NaN
6104              bottled beer

[6105 rows x 4 columns]

In [30]:
# Data Preprocessing 
# check for null values 
df.isnull().sum()

ChildBks     0
YouthBks     0
CookBks      0
DoItYBks     0
RefBks       0
ArtBks       0
GeogBks      0
ItalCook     0
ItalAtlas    0
ItalArt      0
Florence     0
dtype: int64

In [ ]:
# Drop duplicate if any

# Problem statement 3

In [ ]:
''' 
A film distribution company wants to target audience based on their likes and dislikes,
you as a Chief Data Scientist Analyze the data and come up with different rules of movie list so that the business objective is achieved.
3.) my_movies.csv

'''

In [117]:
# Import libraries
import pandas as pd 
df2 = pd.read_csv('my_movies.csv')
df2.head()

,Sixth Sense,Gladiator,LOTR1,Harry Potter1,Patriot,LOTR2,Harry Potter2,LOTR,Braveheart,Green Mile
0,1,0,1,1,0,1,0,0,0,1
1,0,1,0,0,1,0,0,0,1,0
2,0,0,1,0,0,1,0,0,0,0
3,1,1,0,0,1,0,0,0,0,0
4,1,1,0,0,1,0,0,0,0,0

In [120]:
# data preprocessing
# check for missing pvalues 
df2.isnull().sum()

Sixth Sense      0
Gladiator        0
LOTR1            0
Harry Potter1    0
Patriot          0
LOTR2            0
Harry Potter2    0
LOTR             0
Braveheart       0
Green Mile       0
dtype: int64

In [124]:
# drop duplicate rows if aany
df2.drop_duplicates(inplace=True)

In [126]:
# standerize the dataset
from sklearn.preprocessing import StandardScaler
sd = StandardScaler()
sd.fit_transform(df2)

array([[ 1.15470054, -1.15470054,  1.58113883,  1.58113883, -0.8660254 ,
         1.58113883, -0.40824829, -0.40824829, -0.40824829,  1.58113883],
       [-0.8660254 ,  0.8660254 , -0.63245553, -0.63245553,  1.15470054,
        -0.63245553, -0.40824829, -0.40824829,  2.44948974, -0.63245553],
       [-0.8660254 , -1.15470054,  1.58113883, -0.63245553, -0.8660254 ,
         1.58113883, -0.40824829, -0.40824829, -0.40824829, -0.63245553],
       [ 1.15470054,  0.8660254 , -0.63245553, -0.63245553,  1.15470054,
        -0.63245553, -0.40824829, -0.40824829, -0.40824829, -0.63245553],
       [-0.8660254 , -1.15470054, -0.63245553,  1.58113883, -0.8660254 ,
        -0.63245553,  2.44948974, -0.40824829, -0.40824829, -0.63245553],
       [-0.8660254 ,  0.8660254 , -0.63245553, -0.63245553,  1.15470054,
        -0.63245553, -0.40824829, -0.40824829, -0.40824829, -0.63245553],
       [ 1.15470054,  0.8660254 , -0.63245553, -0.63245553, -0.8660254 ,
        -0.63245553, -0.40824829,  2.44948974, -0.40824829,  1.58113883]])

In [128]:
# convert the data set in list formate
# initilize the empty list 
trans = []
for i in range(0,len(df2)):
    trans.append([str(df2.values[i,j]) for j in range(0,len(df2.columns)) if pd.notna(df2.values[i,j])])

print(trans)

[['1', '0', '1', '1', '0', '1', '0', '0', '0', '1'], ['0', '1', '0', '0', '1', '0', '0', '0', '1', '0'], ['0', '0', '1', '0', '0', '1', '0', '0', '0', '0'], ['1', '1', '0', '0', '1', '0', '0', '0', '0', '0'], ['0', '0', '0', '1', '0', '0', '1', '0', '0', '0'], ['0', '1', '0', '0', '1', '0', '0', '0', '0', '0'], ['1', '1', '0', '0', '0', '0', '0', '1', '0', '1']]

In [136]:
# import libraries
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori,association_rules

# convert the dataset into suitable formate as per aapriori
te1 = TransactionEncoder()
ar = te1.fit(trans).transform(trans)
dff = pd.DataFrame(ar, columns=te1.columns_)

In [138]:
# step 2 : apply the apriori algorithm to generate the frequent item
fre = apriori(df2, min_support=0.3, use_colnames=True)

In [140]:
# step 3 : apply the association rules 
apr = association_rules(fre, min_threshold=1, metric='lift')

In [142]:
# display the frequent items
print(fre)

    support              itemsets
0  0.428571         (Sixth Sense)
1  0.571429           (Gladiator)
2  0.428571             (Patriot)
3  0.428571  (Gladiator, Patriot)

In [144]:
print("\n association rule \n")
print(apr[['antecedents','consequents','support','confidence','lift']])

 association rule

   antecedents  consequents   support  confidence  lift
0  (Gladiator)    (Patriot)  0.428571        0.75  1.75
1    (Patriot)  (Gladiator)  0.428571        1.00  1.75

In [ ]:
''' 
Observation:
1. Confidence: When "Gladiator" is purchased, there is a 75% likelihood that "Patriot" is also purchased.
2. Confidence: When "Patriot" is purchased, there is a 100% chance that "Gladiator" is also purchased.
'''

In [ ]:
''' 
Objectve : 3

The objective of this analysis is to apply the Association Rule Algorithm to identify patterns and relationships
between movie purchases at a retail store. Specifically, the goal is to discover how frequently certain movies, 
such as "Gladiator" and "Patriot," are purchased together.
'''

# Problem statement 4

In [ ]:
''' 
Problem Statement: - 
A Mobile Phone manufacturing company wants to launch its three brand new phone into the market, 
but before going with its traditional marketing approach this time it want to analyze the data of its previous model sales 
in different regions and you have been hired as an Data Scientist to help them out, use the Association rules concept and provide your 
insights to the company’s marketing team to improve its sales.
4.) myphonedata.csv
'''

In [149]:
# import the librarise 
import pandas as pd
df3 = pd.read_csv("myphonedata.csv")
df3.head()

   red  white  green  yellow  orange  blue
0    1      1      1       0       0     0
1    0      1      0       0       1     0
2    0      1      0       0       0     1
3    1      1      0       0       1     0
4    1      0      0       0       0     1

In [152]:
# data pre processing 
# check the missing values 
df3.isnull().sum()

red       0
white     0
green     0
yellow    0
orange    0
blue      0
dtype: int64

In [156]:
# drop the duplicate rows
df3.drop_duplicates(inplace=True)

In [158]:
# apply the standerizetion 
from sklearn.preprocessing import StandardScaler

sd1 = StandardScaler()
sd1.fit_transform(df3)

array([[ 1.        ,  0.77459667,  1.73205081, -0.37796447, -0.57735027,
        -0.77459667],
       [-1.        ,  0.77459667, -0.57735027, -0.37796447,  1.73205081,
        -0.77459667],
       [-1.        ,  0.77459667, -0.57735027, -0.37796447, -0.57735027,
         1.29099445],
       [ 1.        ,  0.77459667, -0.57735027, -0.37796447,  1.73205081,
        -0.77459667],
       [ 1.        , -1.29099445, -0.57735027, -0.37796447, -0.57735027,
         1.29099445],
       [ 1.        ,  0.77459667, -0.57735027, -0.37796447, -0.57735027,
         1.29099445],
       [-1.        , -1.29099445,  1.73205081, -0.37796447, -0.57735027,
        -0.77459667],
       [-1.        , -1.29099445, -0.57735027,  2.64575131, -0.57735027,
        -0.77459667]])

In [160]:
# convert the dataset in the form of list 
tran1 = []
for i in range(0, len(df3)):
    tran1.append([str(df3.values[i,j]) for j in range(0, len(df3.columns)) if pd.notna(df3.values[i,j])])

print(tran1)

[['1', '1', '1', '0', '0', '0'], ['0', '1', '0', '0', '1', '0'], ['0', '1', '0', '0', '0', '1'], ['1', '1', '0', '0', '1', '0'], ['1', '0', '0', '0', '0', '1'], ['1', '1', '0', '0', '0', '1'], ['0', '0', '1', '0', '0', '0'], ['0', '0', '0', '1', '0', '0']]

In [162]:
#libraries
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules

In [164]:
# convert the dataset into suitable format
te2 = TransactionEncoder()
arr = te2.fit(tran1).transform(tran1)
df4 = pd.DataFrame(arr, columns=te2.columns_)

In [166]:
# apply the apriori algorithm
fr = apriori(df4, min_support=0.3, use_colnames=True)

In [168]:
# association rule
ass = association_rules(fr, min_threshold=1, metric='lift')

In [170]:
print(fr)

   support itemsets
0      1.0      (0)
1      1.0      (1)
2      1.0   (0, 1)

In [174]:
print("\n association rule \n")
print(apr[['antecedents','consequents','support','confidence','lift']])

 association rule

   antecedents  consequents   support  confidence  lift
0  (Gladiator)    (Patriot)  0.428571        0.75  1.75
1    (Patriot)  (Gladiator)  0.428571        1.00  1.75

In [ ]:
'''
Observation :
1. When "Gladiator" is purchased, there is a 75% confidence that "Patriot" will also be purchased. This indicates a strong association between these two movies.
2. The rule shows a 100% confidence for customers who purchase "Patriot" also purchasing "Gladiator," meaning every customer who bought "Patriot" also bought "Gladiator."
3. The lift value of 1.75 for both rules implies that the likelihood of purchasing "Gladiator" and "Patriot" together is 1.75 times higher than if they were bought independently.
'''

In [ ]:
''' 
Objective :

The goal of this analysis is to identify strong associations between movie purchases at a retail or online store. 
Specifically, by applying association rule mining, we aim to uncover patterns and relationships between different movies that customers frequently purchase together. 
This information can be used to optimize marketing strategies, such as creating targeted promotions, bundling related movies, and improving personalized recommendations,
ultimately leading to increased sales and customer satisfaction. In this case, the strong association between "Gladiator" and "Patriot" offers actionable insights for business decisions.

'''